services:
  backend:
    build: ./backend
    # container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  # jupyter:
  #   build: ./backend
  #   ports:
  #     - "8888:8888"
  #   env_file:
  #     - ./backend/.env
  #   command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser
  #   volumes:
  #     - ./backend:/workspace
  #   depends_on:
  #     - backend